const sampleData = [
  { id: 1, name: "iPhone 15 Pro Max", category: "Mobile" },
  { id: 2, name: "iPhone 13 Mini", category: "Mobile" },
  { id: 3, name: "Samsung Galaxy S23", category: "Mobile" },
  { id: 4, name: "MacBook Pro M3", category: "Laptop" },
  { id: 5, name: "iPhone 12 Pro Max", category: "Mobile" },
  { id: 6, name: "iPhone 7s", category: "Mobile" },
  { id: 7, name: "Samsung Galaxy S24 Ultra", category: "Mobile" },
  { id: 8, name: "MacBook Pro", category: "Laptop" },
  { id: 9, name: "iPhone 15", category: "Mobile" },
  { id: 10, name: "iPhone 12 Mini", category: "Mobile" },
  { id: 11, name: "Samsung Galaxy S20", category: "Mobile" },
  { id: 12, name: "Dell Inspiron", category: "Laptop" },
  { id: 13, name: "iPhone 12 Pro Max", category: "Mobile" },
  { id: 14, name: "iPhone 16 Pro", category: "Mobile" },
  { id: 15, name: "IQOO Neo", category: "Mobile" },
  { id: 16, name: "Lenovo ThinkPad", category: "Laptop" },
  { id: 17, name: "iPhone 14 Pro", category: "Mobile" },
  { id: 18, name: "Samsung Note 10", category: "Mobile" },
  { id: 19, name: "Asus ZenBook", category: "Laptop" },
  { id: 20, name: "iPhone XR", category: "Mobile" },
  { id: 21, name: "Samsung A71", category: "Mobile" },
  { id: 22, name: "HP Pavilion", category: "Laptop" },
  { id: 23, name: "Realme X7", category: "Mobile" },
  { id: 24, name: "Acer Aspire", category: "Laptop" },
  { id: 25, name: "Google Pixel 6", category: "Mobile" },
  { id: 26, name: "Microsoft Surface", category: "Laptop" },
  { id: 27, name: "iPhone SE", category: "Mobile" },
  { id: 28, name: "Lenovo Yoga", category: "Laptop" },
  { id: 29, name: "iPhone 11", category: "Mobile" },
  { id: 30, name: "Asus ROG", category: "Laptop" },
  { id: 31, name: "OnePlus 9", category: "Mobile" },
  { id: 32, name: "Samsung Galaxy Z Flip", category: "Mobile" },
  { id: 33, name: "Dell XPS 13", category: "Laptop" },
  { id: 34, name: "iPhone 8", category: "Mobile" },
  { id: 35, name: "HP Spectre", category: "Laptop" },
  { id: 36, name: "Redmi Note 11", category: "Mobile" },
  { id: 37, name: "Lenovo Legion", category: "Laptop" },
  { id: 38, name: "Samsung Galaxy S10", category: "Mobile" },
  { id: 39, name: "iPhone 6s", category: "Mobile" },
  { id: 40, name: "Acer Predator", category: "Laptop" },
  { id: 41, name: "Oppo Find X", category: "Mobile" },
  { id: 42, name: "Asus VivoBook", category: "Laptop" },
  { id: 43, name: "iPhone 13", category: "Mobile" },
  { id: 44, name: "Dell Latitude", category: "Laptop" },
  { id: 45, name: "Samsung A52", category: "Mobile" },
  { id: 46, name: "MacBook Air M2", category: "Laptop" },
  { id: 47, name: "OnePlus Nord", category: "Mobile" },
  { id: 48, name: "HP Envy", category: "Laptop" },
  { id: 49, name: "iPhone 5", category: "Mobile" },
  { id: 50, name: "Samsung M31", category: "Mobile" },
  { id: 51, name: "Lenovo IdeaPad", category: "Laptop" },
  { id: 52, name: "iPhone XS", category: "Mobile" },
  { id: 53, name: "Google Pixel 7", category: "Mobile" },
  { id: 54, name: "Asus TUF", category: "Laptop" },
  { id: 55, name: "Realme Narzo", category: "Mobile" },
  { id: 56, name: "Microsoft Book", category: "Laptop" },
  { id: 57, name: "Samsung Galaxy S21", category: "Mobile" },
  { id: 58, name: "iPhone 11 Pro", category: "Mobile" },
  { id: 59, name: "Dell G15", category: "Laptop" },
  { id: 60, name: "iPhone X", category: "Mobile" },
  { id: 61, name: "Samsung Galaxy S22", category: "Mobile" },
  { id: 62, name: "HP Omen", category: "Laptop" },
  { id: 63, name: "Redmi K50", category: "Mobile" },
  { id: 64, name: "MacBook Pro M2", category: "Laptop" },
  { id: 65, name: "Oppo Reno 8", category: "Mobile" },
  { id: 66, name: "Lenovo Slim 7", category: "Laptop" },
  { id: 67, name: "iPhone 13 Pro Max", category: "Mobile" },
  { id: 68, name: "Asus Chromebook", category: "Laptop" },
  { id: 69, name: "Realme GT Neo", category: "Mobile" },
  { id: 70, name: "Dell Vostro", category: "Laptop" },
  { id: 71, name: "Samsung A31", category: "Mobile" },
  { id: 72, name: "iPhone 9", category: "Mobile" },
  { id: 73, name: "HP EliteBook", category: "Laptop" },
  { id: 74, name: "OnePlus 10 Pro", category: "Mobile" },
  { id: 75, name: "Acer Swift 5", category: "Laptop" },
  { id: 76, name: "iPhone 14", category: "Mobile" },
  { id: 77, name: "Samsung Fold 3", category: "Mobile" },
  { id: 78, name: "Lenovo Flex", category: "Laptop" },
  { id: 79, name: "iPhone 6", category: "Mobile" },
  { id: 80, name: "Dell Alienware", category: "Laptop" },
  { id: 81, name: "iPhone 11 Mini", category: "Mobile" },
  { id: 82, name: "HP Chromebook", category: "Laptop" },
  { id: 83, name: "Samsung Galaxy Note 9", category: "Mobile" },
  { id: 84, name: "Realme 11 Pro", category: "Mobile" },
  { id: 85, name: "Asus ExpertBook", category: "Laptop" },
  { id: 86, name: "Google Pixel 5", category: "Mobile" },
  { id: 87, name: "MacBook Pro 2021", category: "Laptop" },
  { id: 88, name: "Samsung A12", category: "Mobile" },
  { id: 89, name: "HP Stream", category: "Laptop" },
  { id: 90, name: "iPhone 15 Mini", category: "Mobile" },
  { id: 91, name: "Redmi Note 10 Pro", category: "Mobile" },
  { id: 92, name: "Asus Transformer", category: "Laptop" },
  { id: 93, name: "Lenovo Duet", category: "Laptop" },
  { id: 94, name: "Samsung S10 Lite", category: "Mobile" },
  { id: 95, name: "Realme GT 2", category: "Mobile" },
  { id: 96, name: "iPhone 10", category: "Mobile" },
  { id: 97, name: "MacBook Air M1", category: "Laptop" },
  { id: 98, name: "Samsung A51", category: "Mobile" },
  { id: 99, name: "iPhone 13 Pro", category: "Mobile" },
  { id: 100, name: "Dell Precision", category: "Laptop" },
];

export default sampleData;
